### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by olapxs** [sindrebroch/oslo_waste#1]
I get a  "Failed to set up" error message after running the "Add entry" process.  Have tried with several addresses and the same thing happens. 

My debug log says the following:

> oslo_waste
> Version: 3.0.0
> This is a custom integration!
> If you have any issues with this you need to open an issue here:
> https://github.com/sindrebroch/oslo_waste/issues
> -------------------------------------------------------------------
> 
> 2023-07-18 11:02:54.617 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Oslo waste for oslo_waste
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/oslo_waste/__init__.py", line 34, in async_setup_entry
>     hass.config_entries.async_setup_platforms(entry, PLATFORMS)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by haldorsenc** [comment]
Oslo Waste ver 3.0.0 ?
Hadde ver 2.0 med samme problem. Lasta ned ver 2.0.1b1 og fikk installert.
Foreløpig ser alt ok ut

**Comment by olapxs** [comment]
Ja, dette var på version: 3.0.0
